global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # OpenTelemetry Collector metrics endpoint
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: /metrics

  # OpenTelemetry Collector's own metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: /metrics

  # Promtail log shipper metrics
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
    metrics_path: /metrics

  # Grafana dashboard metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics

  # Loki log aggregator
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: /metrics

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
