basePath: /
definitions:
  model.SimpleDTO:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.SimpleForm:
    properties:
      name:
        type: string
    type: object
  model.UserDTO:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  model.UserForm:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a CRUD API for a simple application.
  title: Go-CRUD API
  version: "1.0"
paths:
  /health:
    get:
      description: Get health of the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get health
      tags:
      - health
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user with email and password
      parameters:
      - description: User email and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserForm'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Login a user
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: Create a new user with email and password
      parameters:
      - description: User email and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserForm'
      produces:
      - application/json
      responses:
        "200":
          description: User created successfully
          schema:
            $ref: '#/definitions/model.UserDTO'
      summary: Sign up a new user
      tags:
      - auth
  /simple:
    get:
      description: Get all Simples
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SimpleDTO'
            type: array
      summary: Get all Simples
      tags:
      - simple
    post:
      consumes:
      - application/json
      description: Create a new Simple
      parameters:
      - description: Simple object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.SimpleForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.SimpleDTO'
      summary: Create a new Simple
      tags:
      - simple
  /simple/{id}:
    delete:
      description: Delete Simple
      parameters:
      - description: Simple ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete Simple
      tags:
      - simple
    get:
      description: Get Simple by ID
      parameters:
      - description: Simple ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SimpleDTO'
      summary: Get Simple by ID
      tags:
      - simple
    put:
      consumes:
      - application/json
      description: Update Simple
      parameters:
      - description: Simple ID
        in: path
        name: id
        required: true
        type: integer
      - description: Simple object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.SimpleForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SimpleDTO'
      summary: Update Simple
      tags:
      - simple
swagger: "2.0"
